# Generated by Django 2.0.4 on 2018-04-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_auto_20180403_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='carrera',
            field=models.CharField(choices=[('sistemas', 'Ingeniería en Sistemas Computacionales'), ('bioquimica', 'Ingeniería Bioquímica'), ('electromecanica', 'Ingeniería Electromecánica'), ('arquitectura', 'Arquitectura'), ('administracion', 'Licenciatura en Administración'), ('contabilidad', 'Contador Público'), ('gestion', 'Ingenieria en Gestión Empresarial')], default='sistemas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Decimo')], default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado',
            field=models.CharField(choices=[('AGU', 'Aguascalientes'), ('BCN', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAM', 'Campeche'), ('CHH', 'Chihuahua'), ('CHP', 'Chiapas'), ('COA', 'Coahuila'), ('COL', 'Colima'), ('DIF', 'Ciudad de México'), ('DUR', 'Durango'), ('GRO', 'Guerrero'), ('GUA', 'Guanajuato'), ('HID', 'Hidalgo'), ('JAL', 'Jalisco'), ('MEX', 'México'), ('MIC', 'Michoacán'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NLE', 'Nuevo León'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QUE', 'Querétaro'), ('ROO', 'Quintana Roo'), ('SIN', 'Sinaloa'), ('SLP', 'San Luis Potosí'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAM', 'Tamaulipas'), ('TLA', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatán'), ('ZAC', 'Zacatecas')], max_length=255),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tipo_registro',
            field=models.CharField(choices=[('alumno', 'Alumno del ITA'), ('exalumno', 'Exalumno del ITA'), ('alumno2', 'Alumno de otra institución'), ('profesional', 'Profesionista')], max_length=255),
        ),
    ]
