# Generated by Django 2.0.4 on 2018-04-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20180414_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='semestre',
            field=models.CharField(choices=[('1', '1 Primero'), ('2', '2 Segundo'), ('3', '3 Tercero'), ('4', '4 Cuarto'), ('5', '5 Quinto'), ('6', '6 Sexto'), ('7', '7 Septimo'), ('8', '8 Octavo'), ('9', '9 Noveno'), ('10', '10 Decimo')], max_length=255),
        ),
    ]
