# Generated by Django 2.0.4 on 2018-04-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20180414_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='state',
            field=models.CharField(choices=[('draft', 'Pendiente'), ('done', 'Confirmado')], default='draft', max_length=255),
            preserve_default=False,
        ),
    ]
