# Generated by Django 2.0.4 on 2018-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0005_registro_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=50)),
                ('intro', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
