# Generated by Django 2.0.4 on 2018-04-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20180417_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='fecha_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
