# Generated by Django 2.0.4 on 2018-04-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20180417_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponente',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponente',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='telefono',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
