# Generated by Django 2.0.4 on 2018-04-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_auto_20180420_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponente',
            name='resumen',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
