# Generated by Django 2.0.4 on 2018-05-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_auto_20180516_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='fecha_hora',
            field=models.DateField(blank=True, null=True),
        ),
    ]
