# Generated by Django 2.0.4 on 2018-05-16 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_auto_20180516_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='tipo',
            field=models.CharField(choices=[('conferencia', 'Conferencia'), ('taller', 'Taller')], default='conferencia', max_length=20),
            preserve_default=False,
        ),
    ]
