# Generated by Django 2.0.4 on 2018-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20180523_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='carrera',
            field=models.CharField(choices=[('arquitectura', 'Arquitectura'), ('bioquimica', 'Ingeniería Bioquímica'), ('electromecanica', 'Ingeniería Electromecánica'), ('sistemas', 'Ingeniería en Sistemas Computacionales'), ('gestion', 'Ingenieria en Gestión Empresarial'), ('administracion', 'Licenciatura en Administración'), ('contabilidad', 'Contador Público')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='fecha_fin',
            field=models.DateField(default='2018-05-11'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='objetivo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='sala',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='duracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
