# Generated by Django 2.0.4 on 2018-05-31 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0018_auto_20180531_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='fecha_modificacion',
            field=models.DateField(default='2018-05-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conferencia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
