# Generated by Django 2.0.4 on 2018-05-31 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_auto_20180531_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='lugar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Lugar'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='ponente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Ponente'),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='sala',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conferencia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
