# Generated by Django 2.0.4 on 2018-05-31 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0020_auto_20180531_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='requisitos',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
