# Generated by Django 2.0.4 on 2018-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_auto_20180531_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='requisitos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
