# Generated by Django 2.0.4 on 2018-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_auto_20180531_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencia',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
