# Generated by Django 2.0.4 on 2018-06-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_auto_20180609_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='nocontrol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
