# Generated by Django 2.0.4 on 2018-06-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0025_auto_20180609_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='carrera',
            field=models.CharField(blank=True, choices=[('sistemas', 'Ingeniería en Sistemas Computacionales'), ('bioquimica', 'Ingeniería Bioquímica'), ('electromecanica', 'Ingeniería Electromecánica'), ('arquitectura', 'Arquitectura'), ('administracion', 'Licenciatura en Administración'), ('contabilidad', 'Contador Público'), ('gestion', 'Ingenieria en Gestión Empresarial')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='semestre',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=255, null=True),
        ),
    ]
