# Generated by Django 2.0.4 on 2018-06-09 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0026_auto_20180609_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default='2018-06-09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
