# Generated by Django 2.0.4 on 2018-06-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0027_auto_20180609_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='user',
        ),
    ]
