# Generated by Django 2.0.4 on 2018-06-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0028_remove_registro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
