# Generated by Django 2.0.4 on 2018-06-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0029_registro_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponente',
            name='tipo',
            field=models.CharField(choices=[('ponente', 'Ponente'), ('profesor', 'Profesor')], default='ponente', max_length=255),
        ),
    ]
