# Generated by Django 2.0.4 on 2018-06-11 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0031_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferencia',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Horario'),
        ),
    ]
