# Generated by Django 2.0.4 on 2018-06-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0032_conferencia_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('nombre', models.CharField(max_length=255)),
                ('requisitos', models.CharField(blank=True, max_length=255, null=True)),
                ('objetivo', models.TextField()),
                ('descripcion', models.TextField()),
                ('profesor', models.CharField(max_length=255)),
                ('salon', models.CharField(max_length=255, null=True)),
                ('fecha', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('duracion', models.IntegerField()),
                ('hora', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('carrera', models.CharField(choices=[('arquitectura', 'Arquitectura'), ('bioquimica', 'Ingeniería Bioquímica'), ('electromecanica', 'Ingeniería Electromecánica'), ('sistemas', 'Ingeniería en Sistemas Computacionales'), ('gestion', 'Ingenieria en Gestión Empresarial'), ('administracion', 'Licenciatura en Administración'), ('contabilidad', 'Contador Público')], max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
