# Generated by Django 2.0.4 on 2018-06-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0033_taller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taller',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
