# Generated by Django 2.0.4 on 2018-06-12 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0034_auto_20180612_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponente',
            name='carrera',
            field=models.CharField(choices=[('arquitectura', 'Arquitectura'), ('bioquimica', 'Ingeniería Bioquímica'), ('electromecanica', 'Ingeniería Electromecánica'), ('sistemas', 'Ingeniería en Sistemas Computacionales'), ('gestion', 'Ingenieria en Gestión Empresarial'), ('administracion', 'Licenciatura en Administración'), ('contabilidad', 'Contador Público')], default='sistemas', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponente',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ponente',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, default='2018-06-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponente',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='registro.Horario'),
        ),
        migrations.AddField(
            model_name='ponente',
            name='ponencia',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ponente',
            name='sala',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ponente',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
