# Generated by Django 2.0.4 on 2018-06-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0035_auto_20180612_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponente',
            name='sala',
        ),
    ]
