# Generated by Django 2.0.4 on 2018-06-12 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0036_remove_ponente_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(choices=[('Dom', 'Domingo'), ('Lun', 'Lunes'), ('Mar', 'Martes'), ('Mie', 'Miercoles'), ('Jue', 'Jueves'), ('Vie', 'Viernes'), ('Sab', 'Sabado')], default='Mie', max_length=10),
        ),
    ]
