# Generated by Django 2.0.4 on 2018-06-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0037_horario_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponente',
            name='foto_ponente',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
