# Generated by Django 2.0.4 on 2018-06-12 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0038_ponente_foto_ponente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponente',
            old_name='foto_ponente',
            new_name='foto_ponencia',
        ),
    ]
