# Generated by Django 2.0.4 on 2018-06-12 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registro', '0039_auto_20180612_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='lugar',
        ),
        migrations.AddField(
            model_name='horario',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
