# Generated by Django 2.0.4 on 2018-06-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0040_auto_20180612_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='registro',
            name='state',
            field=models.CharField(choices=[('draft', 'Nuevo'), ('open', 'Confirmado'), ('done', 'Pagado')], max_length=255),
        ),
    ]
