# Generated by Django 2.0.4 on 2018-06-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0041_auto_20180616_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='genero',
            field=models.CharField(choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], default='hombre', max_length=10),
            preserve_default=False,
        ),
    ]
