# Generated by Django 2.0.4 on 2018-06-21 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0043_auto_20180619_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='pagado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
